# Ejercicio: Extracción de datos de la API de TMDB (The Movie Database)

![imagen](https://www.themoviedb.org/assets/2/v4/logos/v2/blue_square_2-d537fb228cf3ded904ef09b136fe3fec72548ebc1fea3fbbd1ad9e36364db38b.svg)

Trabajaremos con **TMDB**, una de las bases de datos de cine más importantes del mundo. El objetivo es extraer información de películas para realizar un análisis de mercado inicial.

### 1. Registro y Documentación
Tendrás que [registrarte en TMDB](https://www.themoviedb.org/signup) para obtener tu **API Key (v3 auth)** y consultar la [documentación oficial](https://developer.themoviedb.org/reference/intro/getting-started).

### 2. Objetivo del Ejercicio
Queremos que consultes la API para que te devuelva la información de las películas que empiecen por la **inicial de tu nombre** (parámetro `query`). 

Debes guardar la información en un archivo `.csv` con la siguiente estructura de columnas:

| Columna | Descripción |
| :--- | :--- |
| **id** | ID interno de la película en TMDB |
| **title** | Título de la película |
| **release_date** | Fecha de estreno |
| **genres** | Nombres de los géneros (ej: "Acción, Comedia") |
| **vote_average** | Puntuación media de los usuarios |
| **overview** | Sinopsis o resumen de la trama |

### 3. El Reto: Mapeo de Géneros
A diferencia de otras APIs, el endpoint de búsqueda de películas devuelve los géneros como una lista de IDs numéricos (ej: `[28, 12]`). 

**Tu labor es:**
1. Consultar el endpoint de "Genre List" para obtener la relación entre IDs y nombres.
2. Sustituir los IDs en tu DataFrame final por los nombres reales de los géneros (separados por comas).

---

### Código de inicio
Aquí tienes el bloque para empezar a configurar tus llamadas:

```python
import requests
import pandas as pd

# Rellena estas variables
api_key = "TU_API_KEY_AQUÍ"
url_base = "[https://api.themoviedb.org/3](https://api.themoviedb.org/3)"
mi_inicial = "P" # Sustituye por tu inicial

In [20]:
import requests
import pandas as pd

# Configuración
API_KEY = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzOGNjM2M3YzU3ZWJiYzk3ZjNhNGY2Y2YwMDE5MGU5NCIsIm5iZiI6MTc3NDI3ODkwNC4wODcwMDAxLCJzdWIiOiI2OWMxNThmODgwYWNiMzEyZjAwMWQxZjMiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.xznv62VQMu9KLyW4ijySm6gzxnec2urC4B2qCZu_OXA"
url_base = "https://api.themoviedb.org/3"
mi_inicial = "A" # Cambiar por la inicial del alumno

# 1. Obtener el diccionario de géneros (ID -> Nombre)
# Tip: Endpoint /genre/movie/list
def get_genres_map(api_key):
    url = f"{url_base}/genre/movie/list"
    headers = {
        "Authorization": f"Bearer {api_key}"
    }
    response = requests.get(url, headers=headers)
    if response.status_code == 200:
        genres = response.json().get("genres", [])
        return {genre["id"]: genre["name"] for genre in genres}
    else:
        print("Error al obtener los géneros:", response.status_code)
        return {}

# 2. Buscar películas
# Tip: Endpoint /search/movie
def search_movies(api_key, query):
    # Tu código aquí
    # Recordad gestionar la paginación si queréis más de 20 resultados
    url = f"{url_base}/search/movie?query={query}"
    headers = {
        "Authorization": f"Bearer {api_key}"
    }
    response = requests.get(url, headers=headers)
    if response.status_code == 200:
        movies = []
        for movie in response.json().get("results", []):
            movies.append({
                "title": movie["title"],
                "release_date": movie.get("release_date"),
                "genres": movie.get("genre_ids", []),
                "adult": movie.get("adult", False),
                "vote_average": movie.get("vote_average", 0),
                "vote_count": movie.get("vote_count", 0)
            })
        return movies
    else:     
        print("Error al buscar películas:", response.status_code)
        return []

# 3. Procesamiento y Limpieza
# - Mapear los IDs de géneros a nombres reales.
# - Crear el DataFrame.
# - Exportar a CSV.
def process_and_export(movies, genres_map, filename="movies.csv"):
    for movie in movies:
        nombres = []
        for gid in movie["genres"]:
            nombres.append(genres_map.get(gid, "Desconocido"))
        movie["genre_names"] = ", ".join(nombres)
    df = pd.DataFrame(movies)
    # Reordenar columnas para poner genre_names justo después de genres
    cols = list(df.columns)
    cols.remove("genre_names")
    pos = cols.index("genres") + 1
    cols.insert(pos, "genre_names")
    df = df[cols]
    df.to_csv(filename, index=False)
    return df

In [18]:
generos_list = get_genres_map(API_KEY)
generos_df = pd.DataFrame(status.items(), columns=["ID", "Género"])
generos_df

       ID           Género
0      28           Action
1      12        Adventure
2      16        Animation
3      35           Comedy
4      80            Crime
5      99      Documentary
6      18            Drama
7   10751           Family
8      14          Fantasy
9      36          History
10     27           Horror
11  10402            Music
12   9648          Mystery
13  10749          Romance
14    878  Science Fiction
15  10770         TV Movie
16     53         Thriller
17  10752              War
18     37          Western

In [13]:
movies_list = search_movies(API_KEY, "A")
movies_df = pd.DataFrame(movies_list)
movies_df
#movies_df = moviest_df.merge(generos, left_on="genres", right_on="ID", how="left")

,title,release_date,genres,adult,vote_average,vote_count
0,Avatar: Fire and Ash,2025-12-17,"[878, 12, 14]",False,7.300,1927
1,[REC]⁴ Apocalypse,2014-10-31,"[53, 27]",False,5.600,1249
2,Agent Zeta,2026-03-20,"[18, 53]",False,6.800,50
3,The Adolescent,1979-01-24,[18],False,4.300,12
4,A,1965-01-02,[16],False,6.300,37
5,Lilly Lives Alone,2025-08-22,"[27, 53]",False,6.667,3
6,Alpha,2015-01-25,"[27, 18, 9648, 53]",False,5.500,16
7,Anaconda,2025-12-24,"[12, 35, 27]",False,5.882,842
8,A,2017-09-13,"[18, 10402]",False,6.200,205
9,One Battle After Another,2025-09-23,"[53, 80, 35]",False,7.392,3270
10,A,1998-09-09,[99],False,5.900,196
11,BTS THE COMEBACK LIVE | ARIRANG,2026-03-21,[10402],False,9.700,41
12,The Secret Agent,2025-07-23,"[80, 18, 53]",False,7.400,558
13,The Avengers,2012-04-25,"[878, 28, 12]",False,7.977,36706
14,Avengers: Doomsday,2026-12-16,"[878, 28, 12]",False,0.000,0
15,Annelie in the Depths of the Night,2004-12-22,"[14, 10751, 16, 18]",False,0.000,0
16,A...,2013-12-29,[27],False,6.200,2
17,How to Make a Killing,2026-02-19,"[35, 53]",False,7.045,77
18,Abot Langit,2026-03-13,[10749],False,5.000,1
19,Avengers: Infinity War,2018-04-25,"[12, 28, 878]",False,8.234,31639

In [21]:
process_and_export(movies_list, generos_list)

,title,release_date,genres,genre_names,adult,vote_average,vote_count
0,Avatar: Fire and Ash,2025-12-17,"[878, 12, 14]","Science Fiction, Adventure, Fantasy",False,7.300,1927
1,[REC]⁴ Apocalypse,2014-10-31,"[53, 27]","Thriller, Horror",False,5.600,1249
2,Agent Zeta,2026-03-20,"[18, 53]","Drama, Thriller",False,6.800,50
3,The Adolescent,1979-01-24,[18],Drama,False,4.300,12
4,A,1965-01-02,[16],Animation,False,6.300,37
5,Lilly Lives Alone,2025-08-22,"[27, 53]","Horror, Thriller",False,6.667,3
6,Alpha,2015-01-25,"[27, 18, 9648, 53]","Horror, Drama, Mystery, Thriller",False,5.500,16
7,Anaconda,2025-12-24,"[12, 35, 27]","Adventure, Comedy, Horror",False,5.882,842
8,A,2017-09-13,"[18, 10402]","Drama, Music",False,6.200,205
9,One Battle After Another,2025-09-23,"[53, 80, 35]","Thriller, Crime, Comedy",False,7.392,3270
10,A,1998-09-09,[99],Documentary,False,5.900,196
11,BTS THE COMEBACK LIVE | ARIRANG,2026-03-21,[10402],Music,False,9.700,41
12,The Secret Agent,2025-07-23,"[80, 18, 53]","Crime, Drama, Thriller",False,7.400,558
13,The Avengers,2012-04-25,"[878, 28, 12]","Science Fiction, Action, Adventure",False,7.977,36706
14,Avengers: Doomsday,2026-12-16,"[878, 28, 12]","Science Fiction, Action, Adventure",False,0.000,0
15,Annelie in the Depths of the Night,2004-12-22,"[14, 10751, 16, 18]","Fantasy, Family, Animation, Drama",False,0.000,0
16,A...,2013-12-29,[27],Horror,False,6.200,2
17,How to Make a Killing,2026-02-19,"[35, 53]","Comedy, Thriller",False,7.045,77
18,Abot Langit,2026-03-13,[10749],Romance,False,5.000,1
19,Avengers: Infinity War,2018-04-25,"[12, 28, 878]","Adventure, Action, Science Fiction",False,8.234,31639

In [15]:
pelis = pd.read_csv('movies.csv')
pelis

,title,release_date,genre_names,adult,vote_average,vote_count,genre_names.1
0,Avatar: Fire and Ash,2025-12-17,"[878, 12, 14]",False,7.300,1927,"Science Fiction, Adventure, Fantasy"
1,[REC]⁴ Apocalypse,2014-10-31,"[53, 27]",False,5.600,1249,"Thriller, Horror"
2,Agent Zeta,2026-03-20,"[18, 53]",False,6.800,50,"Drama, Thriller"
3,The Adolescent,1979-01-24,[18],False,4.300,12,Drama
4,A,1965-01-02,[16],False,6.300,37,Animation
5,Lilly Lives Alone,2025-08-22,"[27, 53]",False,6.667,3,"Horror, Thriller"
6,Alpha,2015-01-25,"[27, 18, 9648, 53]",False,5.500,16,"Horror, Drama, Mystery, Thriller"
7,Anaconda,2025-12-24,"[12, 35, 27]",False,5.882,842,"Adventure, Comedy, Horror"
8,A,2017-09-13,"[18, 10402]",False,6.200,205,"Drama, Music"
9,One Battle After Another,2025-09-23,"[53, 80, 35]",False,7.392,3270,"Thriller, Crime, Comedy"
10,A,1998-09-09,[99],False,5.900,196,Documentary
11,BTS THE COMEBACK LIVE | ARIRANG,2026-03-21,[10402],False,9.700,41,Music
12,The Secret Agent,2025-07-23,"[80, 18, 53]",False,7.400,558,"Crime, Drama, Thriller"
13,The Avengers,2012-04-25,"[878, 28, 12]",False,7.977,36706,"Science Fiction, Action, Adventure"
14,Avengers: Doomsday,2026-12-16,"[878, 28, 12]",False,0.000,0,"Science Fiction, Action, Adventure"
15,Annelie in the Depths of the Night,2004-12-22,"[14, 10751, 16, 18]",False,0.000,0,"Fantasy, Family, Animation, Drama"
16,A...,2013-12-29,[27],False,6.200,2,Horror
17,How to Make a Killing,2026-02-19,"[35, 53]",False,7.045,77,"Comedy, Thriller"
18,Abot Langit,2026-03-13,[10749],False,5.000,1,Romance
19,Avengers: Infinity War,2018-04-25,"[12, 28, 878]",False,8.234,31639,"Adventure, Action, Science Fiction"