# Fictitious Names

In [123]:
# import numpy as np
import pandas as pd

### Step 2. Create the 3 DataFrames based on the following raw data

In [124]:
raw_data_1 = {
        'subject_id': ['1', '2', '3', '4', '5'],
        'first_name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'], 
        'last_name': ['Anderson', 'Ackerman', 'Ali', 'Aoni', 'Atiches']}

raw_data_2 = {
        'subject_id': ['4', '5', '6', '7', '8'],
        'first_name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'], 
        'last_name': ['Bonder', 'Black', 'Balwner', 'Brice', 'Btisan']}

raw_data_3 = {
        'subject_id': ['1', '2', '3', '4', '5', '7', '8', '9', '10', '11'],
        'test_id': [51, 15, 15, 61, 16, 14, 15, 1, 61, 16]}

In [125]:
raw_data_1 = pd.DataFrame(raw_data_1, columns = ['subject_id', 'first_name', 'last_name'])
raw_data_2 = pd.DataFrame(raw_data_2, columns = ['subject_id', 'first_name', 'last_name'])
raw_data_3 = pd.DataFrame(raw_data_3, columns = ['subject_id', 'test_id'])

### Step 3. Assign each to a variable called data1, data2, data3

### Step 4. Join the two first dataframes along rows and assign to all_data

### Step 5. Join the two first dataframes along columns and assing to all_data_col

### Step 6. Print the unique values of data3

### Step 7. Merge all_data and data3 along the subject_id value

### Step 8. Merge only the data that has the same 'subject_id' on both data1 and data2

### Step 9. Merge all values in data1 and data2, with matching records and not matching records from both sides where available.

In [138]:
data_merged = pd.merge(data1, data2, on='subject_id', how='outer')
data_merged

  subject_id first_name_x last_name_x first_name_y last_name_y
0          1         Alex    Anderson          NaN         NaN
1          2          Amy    Ackerman          NaN         NaN
2          3        Allen         Ali          NaN         NaN
3          4        Alice        Aoni        Billy      Bonder
4          5       Ayoung     Atiches        Brian       Black
5          6          NaN         NaN         Bran     Balwner
6          7          NaN         NaN        Bryce       Brice
7          8          NaN         NaN        Betty      Btisan

In [19]:
pd.merge(data1, data2, on="subject_id", how="outer", suffixes=["_Madrid", "_Valencia"], indicator=True)

,subject_id,first_name_Madrid,last_name_Madrid,first_name_Valencia,last_name_Valencia,_merge
0,1,Alex,Anderson,NaN,NaN,left_only
1,2,Amy,Ackerman,NaN,NaN,left_only
2,3,Allen,Ali,NaN,NaN,left_only
3,4,Alice,Aoni,Billy,Bonder,both
4,5,Ayoung,Atiches,Brian,Black,both
5,6,NaN,NaN,Bran,Balwner,right_only
6,7,NaN,NaN,Bryce,Brice,right_only
7,8,NaN,NaN,Betty,Btisan,right_only

In [20]:
pd.merge(data1, data2, on="subject_id", how="left", suffixes=["_Madrid", "_Valencia"], indicator=True)

,subject_id,first_name_Madrid,last_name_Madrid,first_name_Valencia,last_name_Valencia,_merge
0,1,Alex,Anderson,NaN,NaN,left_only
1,2,Amy,Ackerman,NaN,NaN,left_only
2,3,Allen,Ali,NaN,NaN,left_only
3,4,Alice,Aoni,Billy,Bonder,both
4,5,Ayoung,Atiches,Brian,Black,both