# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv) and assign it to a variable called chipo.

In [2]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep="\t")
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 3. Name of the max valued product

In [ ]:
chipo["item_price"] = chipo["item_price"].str.replace('$', '').astype(float)

In [7]:
chipo[chipo["item_price"] == chipo["item_price"].max()]["item_name"].values[0]

'Chips and Fresh Tomato Salsa'

### Step 4. How many products cost more than $10.00?

In [9]:
chipo[chipo["item_price"] > 10.00].count()

order_id              1130
quantity              1130
item_name             1130
choice_description    1123
item_price            1130
dtype: int64

### Step 4.1: Y cuántos pedidos se han hecho con un producto de más de 10$? Es lo mismo?

In [12]:
chipo[chipo["item_price"] > 10.00]

,order_id,quantity,item_name,choice_description,item_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",10.98
...,...,...,...,...,...
4610,1830,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25

### Step 4.2: Y cuántos pedidos se han hecho de más de 10$? Es lo mismo?

In [13]:
chipo[(chipo["item_price"] > 10.00)]["quantity"].sum()

np.int64(1314)

### Step 4.3: Y en cuántos pedidos se ha pagado más de 10$ por un mismo producto? Es lo mismo?

In [15]:
print(chipo[(chipo["item_price"] > 10.00) & (chipo["quantity"] > 1)].count())
chipo[(chipo["item_price"] > 10.00) & (chipo["quantity"] > 1)]

order_id              133
quantity              133
item_name             133
choice_description    126
item_price            133
dtype: int64

,order_id,quantity,item_name,choice_description,item_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
135,60,2,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Sour Cream, Che...",22.50
148,67,2,Steak Burrito,"[Tomatillo-Red Chili Salsa (Hot), [Rice, Chees...",17.98
150,68,2,Chicken Burrito,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",17.50
154,70,2,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",17.50
...,...,...,...,...,...
4423,1764,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",22.50
4427,1764,2,Steak Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Sour ...",23.50
4435,1767,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",17.50
4489,1786,4,Chips and Guacamole,NaN,17.80
4561,1813,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",17.50

### Step 5. What is the price of each item and name it unit_price. Get only item_name and unit_price

In [57]:
tabla_precios = chipo[["quantity", "item_name", "item_price"]].copy()
tabla_precios["unit_price"] = tabla_precios["item_price"] / tabla_precios["quantity"]
tabla_precios = tabla_precios[["quantity","item_name", "item_price", "unit_price"]].drop_duplicates()
tabla_precios

      quantity                              item_name  item_price  unit_price
0            1           Chips and Fresh Tomato Salsa        2.39        2.39
1            1                                   Izze        3.39        3.39
2            1                       Nantucket Nectar        3.39        3.39
3            1  Chips and Tomatillo-Green Chili Salsa        2.39        2.39
4            2                           Chicken Bowl       16.98        8.49
...        ...                                    ...         ...         ...
4237         2                    Chips and Guacamole        8.50        4.25
4354         2                       Steak Soft Tacos       18.50        9.25
4489         4                    Chips and Guacamole       17.80        4.45
4509         1                                  Chips        1.99        1.99
4510         1                          Barbacoa Bowl       11.49       11.49

[209 rows x 4 columns]

### Step 6. Sort by the name of the item

In [34]:
tabla_precios.sort_values(by = "item_name")

      quantity          item_name  unit_price
3389         2  6 Pack Soft Drink        6.49
298          1  6 Pack Soft Drink        6.49
4510         1      Barbacoa Bowl       11.49
3195         1      Barbacoa Bowl        8.69
95           1      Barbacoa Bowl        9.25
...        ...                ...         ...
186          1  Veggie Salad Bowl       11.25
3889         2  Veggie Soft Tacos        8.49
738          1  Veggie Soft Tacos       11.25
781          1  Veggie Soft Tacos        8.75
1395         1  Veggie Soft Tacos        8.49

[209 rows x 3 columns]

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

In [45]:
print(f'Cantidad de productos: {chipo.loc[chipo["item_price"].idxmax(), "quantity"]}')
print(chipo.loc[chipo["item_price"].idxmax()])

Cantidad de productos: 15
order_id                                      1443
quantity                                        15
item_name             Chips and Fresh Tomato Salsa
choice_description                             NaN
item_price                                   44.25
Name: 3598, dtype: object

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [47]:
print(f'Cantidad de productos: {chipo[chipo["item_price"] == chipo["item_price"].max()]["quantity"].values[0]}')
print(chipo[chipo["item_price"] == chipo["item_price"].max()])

Cantidad de productos: 15
      order_id  quantity                     item_name choice_description  \
3598      1443        15  Chips and Fresh Tomato Salsa                NaN

      item_price
3598       44.25

### Step 9. How many times did someone order more than one Canned Soda?

In [56]:
id = chipo[chipo["item_name"] == "Canned Soda"]["quantity"].idxmax()
chipo.loc[id]

order_id                      901
quantity                        4
item_name             Canned Soda
choice_description       [Sprite]
item_price                   4.36
Name: 2235, dtype: object