# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [5]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv) and assign it to a variable called chipo.

In [6]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep="\t")
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 3. Name of the max valued product

In [7]:
chipo["item_price"] = chipo["item_price"].str.replace('$', '').astype(float)
#creamos una columna con el precio unitario del producto
chipo["unit_price"] = chipo["item_price"] / chipo["quantity"]

In [8]:
chipo

,order_id,quantity,item_name,choice_description,item_price,unit_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,8.49
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75,8.75

In [4]:
chipo[chipo["item_price"] == chipo["item_price"].max()]["item_name"].values[0]

'Chips and Fresh Tomato Salsa'

### Step 4. How many products cost more than $10.00?

In [15]:
chipo[chipo["unit_price"] > 10.00]["item_name"].nunique()

25

### Step 4.1: Y cuántos pedidos se han hecho con un producto de más de 10$? Es lo mismo?

In [18]:
chipo[chipo["unit_price"] > 10.00]

,order_id,quantity,item_name,choice_description,item_price,unit_price
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98,10.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75,11.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",10.98,10.98
39,19,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.75,11.75
...,...,...,...,...,...,...
4610,1830,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,11.75
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25,11.25
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25,11.25

### Step 4.2: Y cuántos pedidos se han hecho de más de 10$? Es lo mismo?

In [13]:
chipo[(chipo["item_price"] > 10.00)]["quantity"].sum()

np.int64(1314)

### Step 4.3: Y en cuántos pedidos se ha pagado más de 10$ por un mismo producto? Es lo mismo?

In [22]:
print(chipo[chipo["item_price"] > 10.00]["order_id"].nunique())

863

### Step 5. What is the price of each item and name it unit_price. Get only item_name and unit_price

In [57]:
tabla_precios = chipo[["quantity", "item_name", "item_price"]].copy()
tabla_precios["unit_price"] = tabla_precios["item_price"] / tabla_precios["quantity"]
tabla_precios = tabla_precios[["quantity","item_name", "item_price", "unit_price"]].drop_duplicates()
tabla_precios

      quantity                              item_name  item_price  unit_price
0            1           Chips and Fresh Tomato Salsa        2.39        2.39
1            1                                   Izze        3.39        3.39
2            1                       Nantucket Nectar        3.39        3.39
3            1  Chips and Tomatillo-Green Chili Salsa        2.39        2.39
4            2                           Chicken Bowl       16.98        8.49
...        ...                                    ...         ...         ...
4237         2                    Chips and Guacamole        8.50        4.25
4354         2                       Steak Soft Tacos       18.50        9.25
4489         4                    Chips and Guacamole       17.80        4.45
4509         1                                  Chips        1.99        1.99
4510         1                          Barbacoa Bowl       11.49       11.49

[209 rows x 4 columns]

### Step 6. Sort by the name of the item

In [34]:
tabla_precios.sort_values(by = "item_name")

      quantity          item_name  unit_price
3389         2  6 Pack Soft Drink        6.49
298          1  6 Pack Soft Drink        6.49
4510         1      Barbacoa Bowl       11.49
3195         1      Barbacoa Bowl        8.69
95           1      Barbacoa Bowl        9.25
...        ...                ...         ...
186          1  Veggie Salad Bowl       11.25
3889         2  Veggie Soft Tacos        8.49
738          1  Veggie Soft Tacos       11.25
781          1  Veggie Soft Tacos        8.75
1395         1  Veggie Soft Tacos        8.49

[209 rows x 3 columns]

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

In [23]:
print(f'Cantidad de productos: {chipo.loc[chipo["item_price"].idxmax(), "quantity"]}')

chipo.loc[chipo["item_price"].idxmax()]

Cantidad de productos: 15

order_id                                      1443
quantity                                        15
item_name             Chips and Fresh Tomato Salsa
choice_description                             NaN
item_price                                   44.25
unit_price                                    2.95
Name: 3598, dtype: object

In [24]:
chipo.sort_values(by = "item_price", ascending = False).head()

,order_id,quantity,item_name,choice_description,item_price,unit_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25,2.95
3480,1398,3,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",35.25,11.75
3602,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",35.00,8.75
1254,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",35.00,8.75
3601,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",33.75,11.25

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [ ]:
lineas_veggie_salad = chipo[chipo["item_name"] == "Veggie Salad Bowl"]

print(lineas_veggie_salad["quantity"].sum())
lineas_veggie_salad

,order_id,quantity,item_name,choice_description,item_price,unit_price
186,83,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
295,128,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",11.25,11.25
455,195,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
496,207,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Rice, Lettuce, Guacamole...",11.25,11.25
960,394,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75,8.75
1316,536,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",8.75,8.75
1884,760,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
2156,869,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25,11.25
2223,896,1,Veggie Salad Bowl,"[Roasted Chili Corn Salsa, Fajita Vegetables]",8.75,8.75
2269,913,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",8.75,8.75
2683,1066,1,Veggie Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75
3223,1289,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25,11.25
3293,1321,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",8.75,8.75
4109,1646,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25,11.25
4201,1677,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",11.25,11.25
4261,1700,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
4541,1805,1,Veggie Salad Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",8.75,8.75
4573,1818,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75,8.75

### Step 9. How many times did someone order more than one Canned Soda?

In [56]:
id = chipo[chipo["item_name"] == "Canned Soda"]["quantity"].idxmax()
chipo.loc[id]

order_id                      901
quantity                        4
item_name             Canned Soda
choice_description       [Sprite]
item_price                   4.36
Name: 2235, dtype: object